version: "3.3"

services:
  server:
    build: .
    ports:
      - "8080:8080"
    secrets:
      - id_rsa
    volumes:
      - type: bind
        source: /home/david/code/indrajala-fluid-client-buildmachine/node
        target: /server/node  
      
secrets:
  id_rsa:
    file: ./resources/secrets/id_rsa