version: "3.3"

services:
  server:
    build: .
    ports:
      - "8080:8080"
    secrets:
      - id_rsa
    volumes:
      - type: bind
        source: /home/david/code/indrajala-fluid-client-buildmachine/node
        target: /server/node  
    environment:
      BS_PORT: ${BS_PORT}
      BS_CHECKOUT_PATH: ${BS_CHECKOUT_PATH}
      BS_PRIVATE_KEY_PATH: ${BS_PRIVATE_KEY_PATH}

secrets:
  id_rsa:
    file: ./resources/secrets/git/id_rsa
  publish_key:
    file: ./resources/secrets/publish/id_rsa